### ISSUE TITLE
Test run is not getting created when test case list is provided 

### ISSUE THREAD

**Issue by nikhilbidave** [devolo/adaptavist#2]
Failed to create test run when test cases list is passed.
Getting below error - 
request failed. 500 Server Error: Internal Server Error for url: https://jira.**.*****.com.**//rest/atm/1.0/testrun {"message":"Unrecognized field \"executedBy\" (Class com.kanoah.testmanager.service.model.TestResultDTO), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@67e7d629; line: 1, column: 205] ............

Code - 
jira_atm.create_test_run(project_key="Test", test_run_name="New", folder="New", test_cases=["Test-T1"])

**Comment by ststeinberg** [comment]
Hi @nikhilbidave, 

That's interesting as it would mean that there's no executedBy field in any executions. Maybe it's due to a misconfiguration of Jira Test management plugin.

Could you please try to call create_test_run without testcases and then to add test cases afterwards by
create_test_results(<test run key>, results=[{"testCaseKey": "Test-T1"}])
?

**Comment by nikhilbidave** [comment]
The test run is getting created when you don't specify test cases. I tried your solution as well but still, test cases are not getting linked to test run.

**Comment by ststeinberg** [comment]
Ok, then it seems that executedBy is just missing in the tm4j plugin. 
Which version of [tm4j](https://marketplace.atlassian.com/apps/1213259/tm4j-test-management-for-jira/version-history) are you using? We are using 6.9.0 currently.
